### ISSUE TITLE
`Running a batch job with derived image`  does not work in Ubuntu

### ISSUE THREAD

**Issue by pskrbasu** [turbot/steampipe-docs#96]
Reference private thread: https://turbothq.slack.com/archives/C01AC8JQNHH/p1668167016349049
Reference steampipe issue: https://github.com/turbot/steampipe/issues/2714

**Comment by johnsmyth** [comment]
We no longer provide a Steampipe container image. Please see https://steampipe.io/docs/faq/overview#where-is-the-dockerfile-or-container-example
